# basic options 
title: Tyler Nimmagadda
email: tylernimmagadda@gmail.com
description: User Experience Research Portflio
show_downloads: [true]

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
